name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go install github.com/google/skicka/gdrive@latest
        go install golang.org/x/crypto/pbkdf2@latest
        go install golang.org/x/net/context@latest
        go install golang.org/x/oauth2@latest
        go install gopkg.in/gcfg.v1@latest
        ls
        go build -v skicka.go

    #- name: Test
    #  run: go test -v ./...
